const BaseJoi = require('joi');
const myError=require('../utils/myError');
//html sanitizing
const sanitizeHtml = require('sanitize-html');

const extension = (joi) => ({
    type: 'string',
    base: joi.string(),
    messages: {
        'string.escapeHTML': '{{#label}} must not include HTML!'
    },
    rules: {
        escapeHTML: {
            validate(value, helpers) {
                const clean = sanitizeHtml(value, {
                    allowedTags: [],
                    allowedAttributes: {},
                });
                if (clean !== value) return helpers.error('string.escapeHTML', { value })
                return clean;
            }
        }
    }
});
const Joi=BaseJoi.extend(extension);

//middleware for data validation(server-side) while making a new dish/editing dish, using Joi schema
const dishjSchema=Joi.object({
    name:Joi.string().required(),
    category:Joi.string().valid('appetizer','mainCourse','bread','drink','dessert').required(),
    description:Joi.string().required(),
    price:Joi.number().required().min(0).max(999),
    _id:Joi.any(),//id- auto generated by mongo db, type:BSON //needed to validate edit route req.body
    __v:Joi.any(),//version - contains the internal revision of the document-auto generate dby mongo db //needed to validate edit route req.body
}).required();

module.exports.validateNewDishData= (req,res,next)=>{
    const {error}=dishjSchema.validate(req.body);
    if(error){
      const msg=error.details.map(e=>e.message).join(',');
      next(new myError(400, msg)); //call error handler with custom error
    }else next();//no error--> go to next function 
};

module.exports.validateEditDishData= (req,res,next)=>{
    const {error}=dishjSchema.validate(req.body);
    if(error){
      const msg=error.details.map(e=>e.message).join(',');
      next(new myError(400, msg)); //call error handler with custom error
    }else next();//no error--> go to next function 
};

//middleware for data validation(server-side) while making a new order/updating order(completed/incomplete), using Joi schema
const orderjSchema=Joi.object({
        name:Joi.string().required(),
        email:Joi.string().email({ minDomainSegments: 2, tlds: { allow: true } }).required(),
        phone:Joi.string().pattern(/^\(([0-9]{3})\)[ ]([0-9]{3})[-]([0-9]{4})$/).required(), //applying check on phone format
        //we have formatted all permitted patterns to (123) 456-7890 before saving order to db
        comments:Joi.string().empty(''),//comments are optional and can be empty string too
        method:Joi.string().required(),
        date:Joi.date().required(),
        time:Joi.number().required().min(0).max(24),
        total:Joi.number().required().min(0),
        completed:Joi.boolean().required(),
        items:Joi.array().required().single(),
        _id:Joi.any(),//id- auto generated by mongo db, type:BSON //needed to validate edit route req.body
        __v:Joi.any(),//version - contains the internal revision of the document-auto generate dby mongo db //needed to validate edit route req.body
    }).required();

module.exports.validateNewOrderData= (req,res,next)=>{
    const {error}=orderjSchema.validate(req.body);
    if(error){
      const msg=error.details.map(e=>e.message).join(',');
      next(new myError(400, msg)); //call error handler with custom error
    }else next();//no error--> go to next function 
};

module.exports.validateEditOrderData= (req,res,next)=>{
    const {error}=orderjSchema.validate(req.body);
    if(error){
      const msg=error.details.map(e=>e.message).join(',');
      next(new myError(400, msg)); //call error handler with custom error
    }else next();//no error--> go to next function 
};
